apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    app: {{ include "postgres.name" . }}
    chart: {{ include "postgres.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ include "postgres.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "postgres.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "postgres.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "postgres.fullname" . }}
      containers:
        - name: postgresql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: postgresql
          env:
            - name: PGDATA
              value: "{{ .Values.persistence.mountPath }}/data"
            - name: POSTGRES_USER
              value: "{{ .Values.postgresqlUser }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresqlPassword }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresqlDatabase }}"
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: postgresql-storage
              mountPath: "{{ .Values.persistence.mountPath }}"
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: postgresql-storage
          persistentVolumeClaim:
            claimName: {{ include "postgres.fullname" . }}-pvc
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: postgresql-storage
        labels:
          app: {{ include "postgres.name" . }}
          release: {{ .Release.Name }}
      spec:
        accessModes: [ "{{ .Values.persistence.accessMode }}" ]
        resources:
          requests:
            storage: "{{ .Values.persistence.size }}"
  {{- end }}
  readinessProbe:
  exec:
    command:
      - pg_isready
      - -U
      - postgres
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

