apiVersion: v1
kind: Service
metadata:
  name: pegaservice
  labels:
    app: pega-web
spec:
  type: LoadBalancer
  selector:
    app: pega-web
  ports:
    - protocol: TCP
      port: 80                     
      targetPort: 8080            
