{{ if ((eq (include "deployNonExtHzSecret" .) "true")) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pega-hz-secret-name" $ }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:

  # Base64 encoded username used for authentication in Hazelcast client-server mode
  {{ if .Values.hazelcast.username -}}
  HZ_CS_AUTH_USERNAME: {{ .Values.hazelcast.username | b64enc }}
  {{ end }}
  # Base64 encoded password used for authentication in Hazelcast client-server mode
  {{ if .Values.hazelcast.password -}}
  HZ_CS_AUTH_PASSWORD: {{ .Values.hazelcast.password | b64enc }}
  {{ end }}
{{ end }}