{{ if (eq (include "performDeployment" .) "true") }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pega-diagnostic-secret-name" $ }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  {{ if and (.Values.global.pegaDiagnosticUser) }}
  # Base64 encoded username for a Tomcat user that will be created with the PegaDiagnosticUser role
  PEGA_DIAGNOSTIC_USER: {{ .Values.global.pegaDiagnosticUser | b64enc }}
  # Base64 encoded password for a Tomcat user that will be created with the PegaDiagnosticUser role
  PEGA_DIAGNOSTIC_PASSWORD: {{ .Values.global.pegaDiagnosticPassword | b64enc }}
  {{ else }}
  {{- /*
  Below is legacy behavior maintained for backward compatibility
  */}}
  {{ range $index, $dep := .Values.global.tier}}
  {{ if and ($dep.pegaDiagnosticUser) (eq $dep.name "web") }}
  # Base64 encoded username for a Tomcat user that will be created with the PegaDiagnosticUser role
  PEGA_DIAGNOSTIC_USER: {{ $dep.pegaDiagnosticUser | b64enc }}
  # Base64 encoded password for a Tomcat user that will be created with the PegaDiagnosticUser role
  PEGA_DIAGNOSTIC_PASSWORD: {{ $dep.pegaDiagnosticPassword | b64enc }}
  {{ end }}
  {{ end }}
  {{ end }}
{{ end }}