{{- if ((eq (include "deployNonExtDBSecret" .) "true")) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pega-db-secret-name" $ }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  # Base64 encoded username for connecting to the Pega DB
  {{ if .Values.global.jdbc.username -}}
  DB_USERNAME: {{ .Values.global.jdbc.username | b64enc }}
  {{- end }}

  # Base64 encoded password for connecting to the Pega DB
  {{ if .Values.global.jdbc.password -}}
  DB_PASSWORD: {{ .Values.global.jdbc.password | b64enc }}
  {{- end }}
{{- end }}